### ISSUE TITLE
Deleting Card with Enrolled Players Yields 500

### ISSUE THREAD

**Issue by sei-jbooz** [cmu-sei/Gameboard#281]
Attempting to delete a game card from the Admin screen yields a hidden 500 error (only visible in dev tools, not in the UI) if the game has players enrolled. The desired behavior would be to either: ask the admin if they wish to delete the game and the enrolled players, or display an error in the UI letting the admin know that the game cannot be deleted while it has players enrolled. 

Steps to Repo: 

1. Create a game 
2. Enroll in the game
3. Attempt to delete the game (observe the 500 error in the dev tools)

**Comment by sei-jbooz** [comment]
```
fail: Gameboard.Api.JsonExceptionMiddleware[0]
      error
      Npgsql.PostgresException (0x80004005): 23503: update or delete on table "Games" violates foreign key constraint "FK_Players_Games_GameId" on table "Players"
      
      DETAIL: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
         at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|234_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Gameboard.Api.Data.Store`1.Delete(String id) in /app/src/Gameboard.Api/Data/Store/Store[TEntity].cs:line 105
         at Gameboard.Api.Services.GameService.Delete(String id) in /app/src/Gameboard.Api/Features/Game/GameService.cs:line 107
         at Gameboard.Api.Controllers.GameController.Delete(String id) in /app/src/Gameboard.Api/Features/Game/GameController.cs:line 113
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Gameboard.Api.FileAuthorizationMiddleware.Invoke(HttpContext context) in /app/src/Gameboard.Api/Structure/FileAuthorizationMiddleware.cs:line 65
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
         at Gameboard.Api.JsonExceptionMiddleware.Invoke(HttpContext context) in /app/src/Gameboard.Api/Extensions/JsonExceptionMiddleware.cs:line 68
        Exception data:
          Severity: ERROR
          SqlState: 23503
          MessageText: update or delete on table "Games" violates foreign key constraint "FK_Players_Games_GameId" on table "Players"
          Detail: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
          SchemaName: public
          TableName: Players
          ConstraintName: FK_Players_Games_GameId
          File: ri_triggers.c
          Line: 2553
          Routine: ri_ReportViolation
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 DELETE http://     /gb/api/game/<id>- - - 500 - - 16.7017ms
```

**Comment by sei-jbooz** [comment]
This is related to #215 but the observations are different. Worth more investigation.

**Comment by sei-bstein** [comment]
We [added](https://github.com/cmu-sei/Gameboard/commit/f15fe75e286706ec4f1a9ff246d53446e360f427) a better error message for this to go out with 3.13.0, but in a future release, we should either:

a) Disable the delete button with an explanation about why, or
b) Enable the deletion of games with registered players if the admin is super sure that's okay (and explain what will happen)
